<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        Product::query()->delete();

        $products = [
            // =========================
            // APPLE (8)
            // =========================
            [
                'brand_id' => 1,
                'name' => 'iPhone SE 2022',
                'slug' => 'iphone-se-2022',
                'price' => 8990000,
                'old_price' => 10990000,
                'quantity' => 8,
                'image' => 'products/iphone-se-2022.jpg',
                'cpu' => 'Apple A15 Bionic',
                'ram' => '4GB',
                'storage' => '64GB',
                'screen' => '4.7 inch Retina HD',
                'gpu' => 'Camera 12MP',
                'os' => 'iOS',
                'weight' => 0.14,
                'description' => 'Mẫu iPhone nhỏ gọn, hiệu năng tốt, phù hợp người thích máy dễ cầm nắm.',
                'is_featured' => false,
            ],
            [
                'brand_id' => 1,
                'name' => 'iPhone 11',
                'slug' => 'iphone-11',
                'price' => 9990000,
                'old_price' => 11990000,
                'quantity' => 10,
                'image' => 'products/iphone-11.jpg',
                'cpu' => 'Apple A13 Bionic',
                'ram' => '4GB',
                'storage' => '64GB',
                'screen' => '6.1 inch Liquid Retina',
                'gpu' => 'Camera kép 12MP',
                'os' => 'iOS',
                'weight' => 0.19,
                'description' => 'Dòng iPhone quốc dân, vẫn đáp ứng tốt nhu cầu học tập và giải trí.',
                'is_featured' => false,
            ],
            [
                'brand_id' => 1,
                'name' => 'iPhone 12',
                'slug' => 'iphone-12',
                'price' => 11490000,
                'old_price' => 13490000,
                'quantity' => 12,
                'image' => 'products/iphone-12.jpg',
                'cpu' => 'Apple A14 Bionic',
                'ram' => '4GB',
                'storage' => '64GB',
                'screen' => '6.1 inch Super Retina XDR',
                'gpu' => 'Camera kép 12MP',
                'os' => 'iOS',
                'weight' => 0.16,
                'description' => 'Thiết kế vuông vức hiện đại, màn hình OLED đẹp và hiệu năng ổn định.',
                'is_featured' => false,
            ],
            [
                'brand_id' => 1,
                'name' => 'iPhone 13',
                'slug' => 'iphone-13',
                'price' => 13490000,
                'old_price' => 15490000,
                'quantity' => 14,
                'image' => 'products/iphone-13.jpg',
                'cpu' => 'Apple A15 Bionic',
                'ram' => '4GB',
                'storage' => '128GB',
                'screen' => '6.1 inch Super Retina XDR',
                'gpu' => 'Camera kép 12MP',
                'os' => 'iOS',
                'weight' => 0.17,
                'description' => 'Phiên bản cân bằng giữa giá, pin và hiệu năng trong hệ sinh thái Apple.',
                'is_featured' => true,
            ],
            [
                'brand_id' => 1,
                'name' => 'iPhone 14',
                'slug' => 'iphone-14',
                'price' => 15990000,
                'old_price' => 17990000,
                'quantity' => 10,
                'image' => 'products/iphone-14.jpg',
                'cpu' => 'Apple A15 Bionic',
                'ram' => '6GB',
                'storage' => '128GB',
                'screen' => '6.1 inch Super Retina XDR',
                'gpu' => 'Camera kép 12MP',
                'os' => 'iOS',
                'weight' => 0.17,
                'description' => 'Mẫu iPhone mới dễ tiếp cận, dùng ổn định và chụp ảnh đẹp.',
                'is_featured' => false,
            ],
            [
                'brand_id' => 1,
                'name' => 'iPhone 15',
                'slug' => 'iphone-15',
                'price' => 18990000,
                'old_price' => 20990000,
                'quantity' => 9,
                'image' => 'products/iphone-15.jpg',
                'cpu' => 'Apple A16 Bionic',
                'ram' => '6GB',
                'storage' => '128GB',
                'screen' => '6.1 inch Super Retina XDR',
                'gpu' => 'Camera 48MP',
                'os' => 'iOS',
                'weight' => 0.17,
                'description' => 'Mẫu iPhone mới với camera cải tiến, hiệu năng mạnh và thiết kế cao cấp.',
                'is_featured' => true,
            ],
            [
                'brand_id' => 1,
                'name' => 'iPhone 15 Pro',
                'slug' => 'iphone-15-pro',
                'price' => 24990000,
                'old_price' => 27990000,
                'quantity' => 6,
                'image' => 'products/iphone-15-pro.jpg',
                'cpu' => 'Apple A17 Pro',
                'ram' => '8GB',
                'storage' => '128GB',
                'screen' => '6.1 inch ProMotion OLED',
                'gpu' => 'Camera Pro 48MP',
                'os' => 'iOS',
                'weight' => 0.19,
                'description' => 'Thiết bị hướng tới người dùng cần hiệu năng cao và camera chuyên nghiệp.',
                'is_featured' => true,
            ],
            [
                'brand_id' => 1,
                'name' => 'iPhone 15 Pro Max',
                'slug' => 'iphone-15-pro-max',
                'price' => 29990000,
                'old_price' => 33990000,
                'quantity' => 5,
                'image' => 'products/iphone-15-pro-max.jpg',
                'cpu' => 'Apple A17 Pro',
                'ram' => '8GB',
                'storage' => '256GB',
                'screen' => '6.7 inch ProMotion OLED',
                'gpu' => 'Camera zoom quang 5x',
                'os' => 'iOS',
                'weight' => 0.22,
                'description' => 'Flagship cao cấp với màn hình lớn, pin tốt và camera zoom mạnh.',
                'is_featured' => true,
            ],

            // =========================
            // SAMSUNG (12)
            // =========================
            [
                'brand_id' => 2,
                'name' => 'Samsung Galaxy A05',
                'slug' => 'samsung-galaxy-a05',
                'price' => 3190000,
                'old_price' => 3690000,
                'quantity' => 20,
                'image' => 'products/galaxy-a05.jpg',
                'cpu' => 'Helio G85',
                'ram' => '4GB',
                'storage' => '128GB',
                'screen' => '6.7 inch PLS LCD',
                'gpu' => 'Camera 50MP',
                'os' => 'Android',
                'weight' => 0.20,
                'description' => 'Mẫu máy phổ thông, phù hợp người cần thiết bị cơ bản giá dễ chịu.',
                'is_featured' => false,
            ],
            [
                'brand_id' => 2,
                'name' => 'Samsung Galaxy A05s',
                'slug' => 'samsung-galaxy-a05s',
                'price' => 3990000,
                'old_price' => 4490000,
                'quantity' => 18,
                'image' => 'products/galaxy-a05s.jpg',
                'cpu' => 'Snapdragon 680',
                'ram' => '6GB',
                'storage' => '128GB',
                'screen' => '6.7 inch FHD+ LCD 90Hz',
                'gpu' => 'Camera 50MP',
                'os' => 'Android',
                'weight' => 0.19,
                'description' => 'Phiên bản nâng cấp nhẹ, hiển thị ổn và pin dùng lâu.',
                'is_featured' => false,
            ],
            [
                'brand_id' => 2,
                'name' => 'Samsung Galaxy A15',
                'slug' => 'samsung-galaxy-a15',
                'price' => 4990000,
                'old_price' => 5790000,
                'quantity' => 18,
                'image' => 'products/galaxy-a15.jpg',
                'cpu' => 'Helio G99',
                'ram' => '8GB',
                'storage' => '128GB',
                'screen' => '6.5 inch Super AMOLED 90Hz',
                'gpu' => 'Camera 50MP',
                'os' => 'Android',
                'weight' => 0.20,
                'description' => 'Mẫu máy phổ thông nổi bật với màn hình đẹp và pin ổn định.',
                'is_featured' => false,
            ],
            [
                'brand_id' => 2,
                'name' => 'Samsung Galaxy A25',
                'slug' => 'samsung-galaxy-a25',
                'price' => 6490000,
                'old_price' => 7490000,
                'quantity' => 16,
                'image' => 'products/galaxy-a25.jpg',
                'cpu' => 'Exynos 1280',
                'ram' => '8GB',
                'storage' => '128GB',
                'screen' => '6.5 inch Super AMOLED 120Hz',
                'gpu' => 'Camera 50MP OIS',
                'os' => 'Android',
                'weight' => 0.20,
                'description' => 'Tầm trung dễ bán, phù hợp học sinh sinh viên và người dùng phổ thông.',
                'is_featured' => false,
            ],
            [
                'brand_id' => 2,
                'name' => 'Samsung Galaxy A35',
                'slug' => 'samsung-galaxy-a35',
                'price' => 7990000,
                'old_price' => 8990000,
                'quantity' => 14,
                'image' => 'products/galaxy-a35.jpg',
                'cpu' => 'Exynos 1380',
                'ram' => '8GB',
                'storage' => '128GB',
                'screen' => '6.6 inch Super AMOLED 120Hz',
                'gpu' => 'Camera 50MP',
                'os' => 'Android',
                'weight' => 0.21,
                'description' => 'Thiết kế đẹp, màn hình lớn, phù hợp người thích Samsung tầm trung.',
                'is_featured' => true,
            ],
            [
                'brand_id' => 2,
                'name' => 'Samsung Galaxy A55',
                'slug' => 'samsung-galaxy-a55',
                'price' => 9990000,
                'old_price' => 11990000,
                'quantity' => 12,
                'image' => 'products/galaxy-a55.jpg',
                'cpu' => 'Exynos 1480',
                'ram' => '8GB',
                'storage' => '128GB',
                'screen' => '6.6 inch Super AMOLED 120Hz',
                'gpu' => 'Camera 50MP',
                'os' => 'Android',
                'weight' => 0.21,
                'description' => 'Một trong những mẫu Samsung tầm trung nổi bật nhất hiện nay.',
                'is_featured' => true,
            ],
            [
                'brand_id' => 2,
                'name' => 'Samsung Galaxy M34',
                'slug' => 'samsung-galaxy-m34',
                'price' => 6590000,
                'old_price' => 7590000,
                'quantity' => 10,
                'image' => 'products/galaxy-m34.jpg',
                'cpu' => 'Exynos 1280',
                'ram' => '8GB',
                'storage' => '128GB',
                'screen' => '6.5 inch Super AMOLED 120Hz',
                'gpu' => 'Camera 50MP',
                'os' => 'Android',
                'weight' => 0.21,
                'description' => 'Dòng M thiên về pin, phù hợp người dùng cần thời lượng sử dụng dài.',
                'is_featured' => false,
            ],
            [
                'brand_id' => 2,
                'name' => 'Samsung Galaxy S21 FE',
                'slug' => 'samsung-galaxy-s21-fe',
                'price' => 10990000,
                'old_price' => 12990000,
                'quantity' => 9,
                'image' => 'products/galaxy-s21-fe.jpg',
                'cpu' => 'Snapdragon 888',
                'ram' => '8GB',
                'storage' => '128GB',
                'screen' => '6.4 inch Dynamic AMOLED 120Hz',
                'gpu' => 'Camera 12MP',
                'os' => 'Android',
                'weight' => 0.18,
                'description' => 'Hiệu năng tốt, màn hình đẹp, vẫn là lựa chọn đáng cân nhắc.',
                'is_featured' => false,
            ],
            [
                'brand_id' => 2,
                'name' => 'Samsung Galaxy S23 FE',
                'slug' => 'samsung-galaxy-s23-fe',
                'price' => 13990000,
                'old_price' => 15990000,
                'quantity' => 8,
                'image' => 'products/galaxy-s23-fe.jpg',
                'cpu' => 'Exynos 2200',
                'ram' => '8GB',
                'storage' => '128GB',
                'screen' => '6.4 inch Dynamic AMOLED 120Hz',
                'gpu' => 'Camera 50MP',
                'os' => 'Android',
                'weight' => 0.20,
                'description' => 'Bản FE mới, hợp người thích trải nghiệm gần flagship với giá mềm hơn.',
                'is_featured' => true,
            ],
            [
                'brand_id' => 2,
                'name' => 'Samsung Galaxy S24',
                'slug' => 'samsung-galaxy-s24',
                'price' => 20990000,
                'old_price' => 23990000,
                'quantity' => 7,
                'image' => 'products/galaxy-s24.jpg',
                'cpu' => 'Exynos 2400',
                'ram' => '8GB',
                'storage' => '256GB',
                'screen' => '6.2 inch Dynamic AMOLED 120Hz',
                'gpu' => 'Camera 50MP',
                'os' => 'Android',
                'weight' => 0.17,
                'description' => 'Flagship nhỏ gọn, mạnh mẽ và phù hợp người dùng cần máy cao cấp.',
                'is_featured' => true,
            ],
            [
                'brand_id' => 2,
                'name' => 'Samsung Galaxy S24 Plus',
                'slug' => 'samsung-galaxy-s24-plus',
                'price' => 25990000,
                'old_price' => 28990000,
                'quantity' => 6,
                'image' => 'products/galaxy-s24-plus.jpg',
                'cpu' => 'Exynos 2400',
                'ram' => '12GB',
                'storage' => '256GB',
                'screen' => '6.7 inch Dynamic AMOLED 120Hz',
                'gpu' => 'Camera 50MP',
                'os' => 'Android',
                'weight' => 0.20,
                'description' => 'Màn hình lớn hơn, pin tốt hơn, trải nghiệm cao cấp toàn diện.',
                'is_featured' => true,
            ],
            [
                'brand_id' => 2,
                'name' => 'Samsung Galaxy S24 Ultra',
                'slug' => 'samsung-galaxy-s24-ultra',
                'price' => 28990000,
                'old_price' => 32990000,
                'quantity' => 5,
                'image' => 'products/galaxy-s24-ultra.jpg',
                'cpu' => 'Snapdragon 8 Gen 3',
                'ram' => '12GB',
                'storage' => '256GB',
                'screen' => '6.8 inch Dynamic AMOLED 120Hz',
                'gpu' => 'Camera 200MP',
                'os' => 'Android',
                'weight' => 0.23,
                'description' => 'Flagship đầu bảng của Samsung với bút S Pen và camera rất mạnh.',
                'is_featured' => true,
            ],

            // =========================
            // XIAOMI (10)
            // =========================
            [
                'brand_id' => 3,
                'name' => 'Xiaomi Redmi 12',
                'slug' => 'xiaomi-redmi-12',
                'price' => 3990000,
                'old_price' => 4690000,
                'quantity' => 18,
                'image' => 'products/redmi-12.jpg',
                'cpu' => 'Helio G88',
                'ram' => '6GB',
                'storage' => '128GB',
                'screen' => '6.79 inch FHD+ LCD 90Hz',
                'gpu' => 'Camera 50MP',
                'os' => 'Android',
                'weight' => 0.20,
                'description' => 'Mẫu máy phổ thông giá mềm, màn hình lớn, phù hợp nhu cầu cơ bản.',
                'is_featured' => false,
            ],
            [
                'brand_id' => 3,
                'name' => 'Xiaomi Redmi Note 12',
                'slug' => 'xiaomi-redmi-note-12',
                'price' => 4990000,
                'old_price' => 5790000,
                'quantity' => 16,
                'image' => 'products/redmi-note-12.jpg',
                'cpu' => 'Snapdragon 685',
                'ram' => '6GB',
                'storage' => '128GB',
                'screen' => '6.67 inch AMOLED 120Hz',
                'gpu' => 'Camera 50MP',
                'os' => 'Android',
                'weight' => 0.19,
                'description' => 'Dòng Redmi Note dễ bán, màn đẹp và hiệu năng ổn cho tầm giá.',
                'is_featured' => false,
            ],
            [
                'brand_id' => 3,
                'name' => 'Xiaomi Redmi Note 13',
                'slug' => 'xiaomi-redmi-note-13',
                'price' => 5790000,
                'old_price' => 6590000,
                'quantity' => 15,
                'image' => 'products/redmi-note-13.jpg',
                'cpu' => 'Snapdragon 685',
                'ram' => '8GB',
                'storage' => '128GB',
                'screen' => '6.67 inch AMOLED 120Hz',
                'gpu' => 'Camera 108MP',
                'os' => 'Android',
                'weight' => 0.19,
                'description' => 'Bản nâng cấp hợp lý, phù hợp người dùng phổ thông muốn camera đẹp.',
                'is_featured' => true,
            ],
            [
                'brand_id' => 3,
                'name' => 'Xiaomi Redmi Note 13 Pro',
                'slug' => 'xiaomi-redmi-note-13-pro',
                'price' => 7990000,
                'old_price' => 8990000,
                'quantity' => 12,
                'image' => 'products/redmi-note-13-pro.jpg',
                'cpu' => 'Snapdragon 7s Gen 2',
                'ram' => '8GB',
                'storage' => '256GB',
                'screen' => '6.67 inch AMOLED 120Hz',
                'gpu' => 'Camera 200MP',
                'os' => 'Android',
                'weight' => 0.21,
                'description' => 'Một trong những mẫu Xiaomi tầm trung nổi bật nhờ camera và màn hình.',
                'is_featured' => true,
            ],
            [
                'brand_id' => 3,
                'name' => 'Xiaomi POCO M6',
                'slug' => 'xiaomi-poco-m6',
                'price' => 4490000,
                'old_price' => 5190000,
                'quantity' => 14,
                'image' => 'products/poco-m6.jpg',
                'cpu' => 'Helio G91',
                'ram' => '6GB',
                'storage' => '128GB',
                'screen' => '6.79 inch LCD 90Hz',
                'gpu' => 'Camera 108MP',
                'os' => 'Android',
                'weight' => 0.21,
                'description' => 'Máy phổ thông thiên về cấu hình và giá bán cạnh tranh.',
                'is_featured' => false,
            ],
            [
                'brand_id' => 3,
                'name' => 'Xiaomi POCO X6',
                'slug' => 'xiaomi-poco-x6',
                'price' => 7490000,
                'old_price' => 8490000,
                'quantity' => 12,
                'image' => 'products/poco-x6.jpg',
                'cpu' => 'Snapdragon 7s Gen 2',
                'ram' => '8GB',
                'storage' => '256GB',
                'screen' => '6.67 inch AMOLED 120Hz',
                'gpu' => 'Camera 64MP',
                'os' => 'Android',
                'weight' => 0.19,
                'description' => 'POCO thiên hiệu năng, phù hợp người dùng trẻ và game nhẹ.',
                'is_featured' => true,
            ],
            [
                'brand_id' => 3,
                'name' => 'Xiaomi POCO X6 Pro',
                'slug' => 'xiaomi-poco-x6-pro',
                'price' => 8990000,
                'old_price' => 9990000,
                'quantity' => 10,
                'image' => 'products/poco-x6-pro.jpg',
                'cpu' => 'Dimensity 8300 Ultra',
                'ram' => '12GB',
                'storage' => '256GB',
                'screen' => '6.67 inch AMOLED 120Hz',
                'gpu' => 'Camera 64MP',
                'os' => 'Android',
                'weight' => 0.19,
                'description' => 'Hiệu năng mạnh trong tầm giá, phù hợp người thích chơi game.',
                'is_featured' => true,
            ],
            [
                'brand_id' => 3,
                'name' => 'Xiaomi POCO F5',
                'slug' => 'xiaomi-poco-f5',
                'price' => 9990000,
                'old_price' => 11990000,
                'quantity' => 9,
                'image' => 'products/poco-f5.jpg',
                'cpu' => 'Snapdragon 7+ Gen 2',
                'ram' => '12GB',
                'storage' => '256GB',
                'screen' => '6.67 inch AMOLED 120Hz',
                'gpu' => 'Camera 64MP',
                'os' => 'Android',
                'weight' => 0.18,
                'description' => 'Mẫu máy thiên hiệu năng nổi tiếng của POCO.',
                'is_featured' => true,
            ],
            [
                'brand_id' => 3,
                'name' => 'Xiaomi 13T',
                'slug' => 'xiaomi-13t',
                'price' => 12990000,
                'old_price' => 14990000,
                'quantity' => 8,
                'image' => 'products/xiaomi-13t.jpg',
                'cpu' => 'Dimensity 8200 Ultra',
                'ram' => '12GB',
                'storage' => '256GB',
                'screen' => '6.67 inch AMOLED 144Hz',
                'gpu' => 'Camera Leica 50MP',
                'os' => 'Android',
                'weight' => 0.20,
                'description' => 'Tập trung vào trải nghiệm cao cấp hơn ở camera và màn hình.',
                'is_featured' => true,
            ],
            [
                'brand_id' => 3,
                'name' => 'Xiaomi 14',
                'slug' => 'xiaomi-14',
                'price' => 19990000,
                'old_price' => 22990000,
                'quantity' => 6,
                'image' => 'products/xiaomi-14.jpg',
                'cpu' => 'Snapdragon 8 Gen 3',
                'ram' => '12GB',
                'storage' => '256GB',
                'screen' => '6.36 inch AMOLED 120Hz',
                'gpu' => 'Camera Leica 50MP',
                'os' => 'Android',
                'weight' => 0.19,
                'description' => 'Flagship của Xiaomi với hiệu năng mạnh và camera cao cấp.',
                'is_featured' => true,
            ],

            // =========================
            // OPPO (10)
            // =========================
            [
                'brand_id' => 4,
                'name' => 'OPPO A38',
                'slug' => 'oppo-a38',
                'price' => 4190000,
                'old_price' => 4890000,
                'quantity' => 16,
                'image' => 'products/oppo-a38.jpg',
                'cpu' => 'Helio G85',
                'ram' => '6GB',
                'storage' => '128GB',
                'screen' => '6.56 inch HD+ LCD 90Hz',
                'gpu' => 'Camera 50MP',
                'os' => 'Android',
                'weight' => 0.19,
                'description' => 'Mẫu OPPO phổ thông phù hợp người cần máy cơ bản dễ dùng.',
                'is_featured' => false,
            ],
            [
                'brand_id' => 4,
                'name' => 'OPPO A58',
                'slug' => 'oppo-a58',
                'price' => 4990000,
                'old_price' => 5790000,
                'quantity' => 14,
                'image' => 'products/oppo-a58.jpg',
                'cpu' => 'Helio G85',
                'ram' => '6GB',
                'storage' => '128GB',
                'screen' => '6.72 inch FHD+ LCD',
                'gpu' => 'Camera 50MP',
                'os' => 'Android',
                'weight' => 0.19,
                'description' => 'Thiết kế trẻ trung, dễ bán trong phân khúc phổ thông.',
                'is_featured' => false,
            ],
            [
                'brand_id' => 4,
                'name' => 'OPPO A78',
                'slug' => 'oppo-a78',
                'price' => 5990000,
                'old_price' => 6990000,
                'quantity' => 13,
                'image' => 'products/oppo-a78.jpg',
                'cpu' => 'Snapdragon 680',
                'ram' => '8GB',
                'storage' => '256GB',
                'screen' => '6.43 inch AMOLED 90Hz',
                'gpu' => 'Camera 50MP',
                'os' => 'Android',
                'weight' => 0.18,
                'description' => 'Mẫu máy tầm trung cân bằng giữa thiết kế, màn hình và pin.',
                'is_featured' => true,
            ],
            [
                'brand_id' => 4,
                'name' => 'OPPO A79',
                'slug' => 'oppo-a79',
                'price' => 6990000,
                'old_price' => 7990000,
                'quantity' => 12,
                'image' => 'products/oppo-a79.jpg',
                'cpu' => 'Dimensity 6020',
                'ram' => '8GB',
                'storage' => '256GB',
                'screen' => '6.72 inch FHD+ LCD 90Hz',
                'gpu' => 'Camera 50MP',
                'os' => 'Android',
                'weight' => 0.19,
                'description' => 'Máy 5G tầm trung, phù hợp người dùng thích thương hiệu OPPO.',
                'is_featured' => false,
            ],
            [
                'brand_id' => 4,
                'name' => 'OPPO A98',
                'slug' => 'oppo-a98',
                'price' => 7490000,
                'old_price' => 8490000,
                'quantity' => 10,
                'image' => 'products/oppo-a98.jpg',
                'cpu' => 'Snapdragon 695',
                'ram' => '8GB',
                'storage' => '256GB',
                'screen' => '6.72 inch FHD+ LCD 120Hz',
                'gpu' => 'Camera 64MP',
                'os' => 'Android',
                'weight' => 0.19,
                'description' => 'Dòng A cao hơn, cấu hình tốt và trải nghiệm ổn định.',
                'is_featured' => false,
            ],
            [
                'brand_id' => 4,
                'name' => 'OPPO Reno8 T',
                'slug' => 'oppo-reno8-t',
                'price' => 7990000,
                'old_price' => 8990000,
                'quantity' => 9,
                'image' => 'products/oppo-reno8-t.jpg',
                'cpu' => 'Snapdragon 695',
                'ram' => '8GB',
                'storage' => '256GB',
                'screen' => '6.7 inch AMOLED 120Hz',
                'gpu' => 'Camera 108MP',
                'os' => 'Android',
                'weight' => 0.18,
                'description' => 'Thiết kế thời trang, hợp nhóm khách hàng thích chụp ảnh và máy đẹp.',
                'is_featured' => true,
            ],
            [
                'brand_id' => 4,
                'name' => 'OPPO Reno10',
                'slug' => 'oppo-reno10',
                'price' => 10990000,
                'old_price' => 12490000,
                'quantity' => 8,
                'image' => 'products/oppo-reno10.jpg',
                'cpu' => 'Snapdragon 778G',
                'ram' => '8GB',
                'storage' => '256GB',
                'screen' => '6.7 inch AMOLED 120Hz',
                'gpu' => 'Camera chân dung tele',
                'os' => 'Android',
                'weight' => 0.18,
                'description' => 'Dòng Reno thiên về thiết kế và camera chân dung.',
                'is_featured' => true,
            ],
            [
                'brand_id' => 4,
                'name' => 'OPPO Reno11',
                'slug' => 'oppo-reno11',
                'price' => 11990000,
                'old_price' => 13990000,
                'quantity' => 7,
                'image' => 'products/oppo-reno11.jpg',
                'cpu' => 'Dimensity 7050',
                'ram' => '12GB',
                'storage' => '256GB',
                'screen' => '6.7 inch AMOLED 120Hz',
                'gpu' => 'Camera 50MP',
                'os' => 'Android',
                'weight' => 0.18,
                'description' => 'Thiết kế đẹp, máy mỏng nhẹ và hướng tới trải nghiệm camera.',
                'is_featured' => true,
            ],
            [
                'brand_id' => 4,
                'name' => 'OPPO Reno11 F',
                'slug' => 'oppo-reno11-f',
                'price' => 8990000,
                'old_price' => 9990000,
                'quantity' => 8,
                'image' => 'products/oppo-reno11-f.jpg',
                'cpu' => 'Dimensity 7050',
                'ram' => '8GB',
                'storage' => '256GB',
                'screen' => '6.7 inch AMOLED 120Hz',
                'gpu' => 'Camera 64MP',
                'os' => 'Android',
                'weight' => 0.18,
                'description' => 'Phiên bản dễ tiếp cận hơn của Reno11, vẫn giữ thiết kế đẹp mắt.',
                'is_featured' => false,
            ],
            [
                'brand_id' => 4,
                'name' => 'OPPO Find X7',
                'slug' => 'oppo-find-x7',
                'price' => 21990000,
                'old_price' => 24990000,
                'quantity' => 5,
                'image' => 'products/oppo-find-x7.jpg',
                'cpu' => 'Dimensity 9300',
                'ram' => '12GB',
                'storage' => '256GB',
                'screen' => '6.78 inch AMOLED 120Hz',
                'gpu' => 'Camera Hasselblad 50MP',
                'os' => 'Android',
                'weight' => 0.21,
                'description' => 'Flagship đầu bảng của OPPO với hiệu năng mạnh và camera cao cấp.',
                'is_featured' => true,
            ],
        ];

        foreach ($products as $product) {
            Product::create([
                'brand_id' => $product['brand_id'],
                'name' => $product['name'],
                'slug' => $product['slug'],
                'price' => $product['price'],
                'old_price' => $product['old_price'],
                'quantity' => $product['quantity'],
                'image' => $product['image'],
                'cpu' => $product['cpu'],
                'ram' => $product['ram'],
                'storage' => $product['storage'],
                'screen' => $product['screen'],
                'gpu' => $product['gpu'],
                'os' => $product['os'],
                'weight' => $product['weight'],
                'description' => $product['description'],
                'is_featured' => $product['is_featured'],
            ]);
        }
    }
}